### ISSUE TITLE
Windows test failure

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-codec-collectd#3]
From https://github.com/elasticsearch/logstash/issues/2487

These failures are likely due to the fact that `file-dependencies` post-install hook isn't being invoked?

```
  61) LogStash::Codecs::Collectd Replace nan_value and nan_tag with non-default values should replace a NaN with the specified value and tag 'NaN_encountered'
     Failure/Error: next LogStash::Codecs::Collectd.new({"nan_value" => 1,
     RuntimeError:
       You must specify 'typesdb => ...' in your collectd input (I looked for 'C:/Users/jls/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-collectd-0.1.3/vendor/types.db')
     # ./lib/logstash/codecs/base.rb:15:in `initialize'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  62) LogStash::Codecs::Collectd Encrypt should not parse unencrypted packets when encrypt is configured
     Failure/Error: next LogStash::Codecs::Collectd.new({"authfile" => authfile.path,
     RuntimeError:
       You must specify 'typesdb => ...' in your collectd input (I looked for 'C:/Users/jls/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-collectd-0.1.3/vendor/types.db')
     # ./lib/logstash/codecs/base.rb:15:in `initialize'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  63) LogStash::Codecs::Collectd Drop NaN event should drop an event with a NaN value when 'nan_handling' set to drop
     Failure/Error: next LogStash::Codecs::Collectd.new({"nan_handling" => "drop"})
     RuntimeError:
       You must specify 'typesdb => ...' in your collectd input (I looked for 'C:/Users/jls/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-collectd-0.1.3/vendor/types.db')
     # ./lib/logstash/codecs/base.rb:15:in `initialize'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  64) LogStash::Codecs::Collectd Sign should parse a correctly signed packet
     Failure/Error: next LogStash::Codecs::Collectd.new({"authfile" => authfile.path,
     RuntimeError:
       You must specify 'typesdb => ...' in your collectd input (I looked for 'C:/Users/jls/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-collectd-0.1.3/vendor/types.db')
     # ./lib/logstash/codecs/base.rb:15:in `initialize'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  65) LogStash::Codecs::Collectd Sign should not parse an incorrectly signed packet
     Failure/Error: next LogStash::Codecs::Collectd.new({"authfile" => authfile.path,
     RuntimeError:
       You must specify 'typesdb => ...' in your collectd input (I looked for 'C:/Users/jls/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-collectd-0.1.3/vendor/types.db')
     # ./lib/logstash/codecs/base.rb:15:in `initialize'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  66) LogStash::Codecs::Collectd Warn on NaN event should replace a NaN with a zero and receive a warning when 'nan_handling' set to warn
     Failure/Error: next LogStash::Codecs::Collectd.new({"nan_handling" => "warn"})
     RuntimeError:
       You must specify 'typesdb => ...' in your collectd input (I looked for 'C:/Users/jls/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-collectd-0.1.3/vendor/types.db')
     # ./lib/logstash/codecs/base.rb:15:in `initialize'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  67) LogStash::Codecs::Collectd None should drop a part with an header length
     Failure/Error: next LogStash::Codecs::Collectd.new({})
     RuntimeError:
       You must specify 'typesdb => ...' in your collectd input (I looked for 'C:/Users/jls/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-collectd-0.1.3/vendor/types.db')
     # ./lib/logstash/codecs/base.rb:15:in `initialize'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  68) LogStash::Codecs::Collectd None should replace a NaN with a zero and add tag '_collectdNaN' by default
     Failure/Error: next LogStash::Codecs::Collectd.new({})
     RuntimeError:
       You must specify 'typesdb => ...' in your collectd input (I looked for 'C:/Users/jls/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-collectd-0.1.3/vendor/types.db')
     # ./lib/logstash/codecs/base.rb:15:in `initialize'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  69) LogStash::Codecs::Collectd None should parse a normal packet
     Failure/Error: next LogStash::Codecs::Collectd.new({})
     RuntimeError:
       You must specify 'typesdb => ...' in your collectd input (I looked for 'C:/Users/jls/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-collectd-0.1.3/vendor/types.db')
     # ./lib/logstash/codecs/base.rb:15:in `initialize'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'
```
